### ISSUE TITLE
Don't re-sort the room list (or mark rooms as unread) based on nick or profile changes

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#110]
Events that trigger this issue include:

- [ ] Changing/setting/unsetting profile photo
- [ ] Updating nick

**Comment by dkasak** [comment]
I just stumbled on this in the new design and I can imagine it would be rather odd looking for the average user (from a polish perspective), so just bumping this. Perhaps it could now be tracked as part of the redesign process?

**Comment by turt2live** [comment]
We fixed this accidentally in the new room list.

**Comment by ara4n** [comment]
Empirically we didn't. neil just changed his name to neil_away, causing every room I share with him to rise to the top of the "sort by activity" room lists.

**Comment by t3chguy** [comment]
AIUI this will be implicitly fixed by the FTUE Notifications project changing the causes of `unread` and consolidating bold & unread

**Comment by benparsons** [comment]
This is especially annoying if you change your name - my old DMs are now in a random order

**Comment by ara4n** [comment]
I am constantly chasing unread room badges only to discover that it’s someone having changed their name. This is particularly problematic where people are changing their displayname as a poor man’s form of custom presence, which has got more popular recently.

Is there a solution which isn’t blocked in the FTUE Notifications project?

**Comment by turt2live** [comment]
the room list store should be capable of filtering out event types for the timestamp comparison, thus not updating as often.

**Comment by ara4n** [comment]
Somehow, this is still happening, perhaps due to https://github.com/matrix-org/synapse/issues/9716. Reopening it to keep it on the EW radar.
