### ISSUE TITLE
** Unable to decrypt: The sender's device has not sent us the keys for this message. **

### ISSUE THREAD

**Issue by kevincox** [vector-im/element-web#16163]
### Description

Can't read the message. Sent between devices that have been talking using e2ee for a long time.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: develop.element.io / app.element.io / somewhere else? If a private server, what version of Element Web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by kevincox** [comment]
This was mostly to send logs which have been sent from the element-web interface. However I can not decrypt on any of my devices.

**Comment by kevincox** [comment]
Related to https://github.com/vector-im/element-web/issues/2996

**Comment by kevincox** [comment]
It is worth noting that subsequent messages sent from the same device were perfectly fine.

**Comment by jryans** [comment]
I have forwarded this issue to our E2EE team to investigate what's going wrong here.

**Comment by kevincox** [comment]
Thanks, this is ongoing. We just had an extended period of this issue today and I asked the sender to send logs from the Android app referencing this issue.

FWIW I now believe that this is an element-android issue as I think the sending device is to blame.

**Comment by kevincox** [comment]
This instance has been restored when the app cache was cleared. Usually we didn't clear the cache, it just recovered on its own but this time it went on for an extended period of time so I suggested that the sender clear the cache. It could have been coincidence but messages sent after the cache clear were readable to all devices.

I also confirmed that the sender uploaded logs from the app. They did a shake and sent this URL in the description.

**Comment by uhoreg** [comment]
I was unable to do much with the first set of debug logs because we don't have the logs from the sender.  With the second set, it looks like the problem started with a spurious network error on the sender's side.  In theory, it should have been able to recover, but it could be that it's not working properly.

**Comment by kevincox** [comment]
This is on a mobile phone so flakey network is likely if not expected.

**Comment by ssbothwell** [comment]
> This instance has been restored when the app cache was cleared. Usually we didn't clear the cache, it just recovered on its own but this time it went on for an extended period of time so I suggested that the sender clear the cache. It could have been coincidence but messages sent after the cache clear were readable to all devices.
> 
> I also confirmed that the sender uploaded logs from the app. They did a shake and sent this URL in the description.

How do you clear the app cache?

**Comment by jryans** [comment]
> How do you clear the app cache?

Top left user menu -> Settings -> Help -> Scroll down -> Click "Clear cache and reload" button

**Comment by akhilman** [comment]
I have similar issue.

The interlocutor can read my messages, but I can't read his messages with ``Unable to decrypt: The sender's device has not sent us the keys for this message`` error.

A while ago I had reset my keys by Settings -> Security & Privacy -> Encryption -> Secure Backup -> Reset. Since that I never able to read any message from my friend. The problem continues more than half of the year. We tried many times to create a new room. We also tried different clients, including element-web with multiple browser, nheko, fluffychat in my side, and element-web and element-android on another side. Always same result.

Here is recent try:
Room ID: !nAkgXNdTyzUuREuqGI:ru-matrix.org
My ID: @akhil:ru-matrix.org
Interlocutor's ID: @s6:matrix.org

From my side:
![image](https://user-images.githubusercontent.com/180812/128616199-a13f6c1d-a28d-4f31-b0b0-33aa1df98712.png)
[akhil.log](https://github.com/vector-im/element-web/files/6950008/akhil.log)

From interlocutor's side:
![image](https://user-images.githubusercontent.com/180812/128619950-c9ddad3a-beb8-497c-957c-fcaaad8f867f.png)
[s6.log](https://github.com/vector-im/element-web/files/6950009/s6.log)

**Comment by akhilman** [comment]
My issue solved by server admin. It was instance of https://github.com/matrix-org/synapse/issues/6867.

**Comment by k79e** [comment]
Have this problem too,
One of friend reinstalled the system, I think he formatted the partition,
So the old keys is deleted.

Now He says all information from a date (when he is not online) I sent to him is un-readable. It's can't decrypt.

But after he is online, we can normally chat, But he still can't read the information in above mentioned period.

**Comment by richvdh** [comment]
Duplicate of https://github.com/vector-im/element-meta/issues/245
