### ISSUE TITLE
Being in a space but not its subspaces doesn't show grandchild rooms

### ISSUE THREAD

**Issue by williamkray** [vector-im/element-web#17293]
![Screenshot_20210513102222](https://user-images.githubusercontent.com/8409433/118162297-6cd16400-b3d5-11eb-87c2-6c22a175e30b.png)

### Description
Joining a new community (#community:matrix.org) which has many rooms I am already a member of, most of those rooms did not render properly in the Spaces panel. Exploring rooms shows that I am indeed in the room by showing me a "View" button instead of "Join". However, clicking "View" takes me back to the Home (All Spaces) space to show me the room.

Logs being sent: yes

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: Arch Linux
- **URL**: develop.element.io

**Comment by SimonBrandner** [comment]
Can repro on desktop

**Comment by SimonBrandner** [comment]
Clearing cache doesn't seem to fix this either

**Comment by SimonBrandner** [comment]
Ok, I don't think I can repro this with other spaces... Can someone please confirm this? Could the space be broken?

**Comment by t3chguy** [comment]
So the issue above is because that room is in a subspace and you haven't joined the subspace

**Comment by williamkray** [comment]
that... makes complete sense. i didn't put that together despite having already experienced that with the testing space.

**Comment by toger5** [comment]
@t3chguy This makes sense.
When peek is available, will that be the default behavior? showing grandchild?
Or is would that be optional?
Imo showing it be default is what I would have expected.

**Comment by t3chguy** [comment]
Product/Design hasn't investigated this yet to my knowledge so no idea.

**Comment by clokep** [comment]
> So the issue above is because that room is in a subspace and you haven't joined the subspace.
> This is a known limitation until we have the `/peek` API to watch those not-yet-joined subspaces.

I think that was a potential solution, but I think the root cause was that the spaces summary previously did not recurse into rooms which had join rules of `public` (matrix-org/synapse#10298) as well as some other bugs if you had a pending invite to a space, etc.

I *think* this should be fixed as of Synapse 1.39.0.

Note that the current spaces summary for #community:matrix.org still might not be 100% accurate until pagination is complete. Server-side support for this was done (and is in Synapse 1.41.0), but Element Web needs an update for it still.

**Comment by novocaine** [comment]
@williamkray can you check if things have improved for you please?

**Comment by williamkray** [comment]
yes, i'm seeing lots more rooms in the subspaces!

**Comment by williamkray** [comment]
@clokep you are correct, i lost track of why i originally opened this ticket in the first place. thank you for reminding me.

i have _left_ the "bots" subspace of the matrix community, and the left panel still does not show me those rooms when i have selected the matrix community space. instead, those rooms are only visible when i visit the "home" metaspace.

i would expect that because these rooms are grandchildren of the matrix community space, they would still show up under that space, regardless of whether i am a member of their requisite sub-space.

**Comment by clokep** [comment]
Thanks! I've reopened this then (and tried to clarify the title a bit).

**Comment by novocaine** [comment]
This is annoying, but downgrading severity to S-minor as this doesn't severely degrade major functionality

**Comment by novocaine** [comment]
@kittykat convinced me that this is S-Major as she's lost track of rooms without understanding why

**Comment by t3chguy** [comment]
Subspaces are still marked as Beta though

**Comment by novocaine** [comment]
> Subspaces are still marked as Beta though

yeah, that occurred to me but we don't really have a great way to express that in labels..

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/132029063-df24fd8a-0b0a-4ea2-a3ff-dc9d33760cb8.png)

> Severely degrades major functionality or product features, with no satisfactory workaround

Just going off the label description, surely a Beta feature shouldn't be considered "major functionality" and it does have a workaround

**Comment by edrex** [comment]
I'd like to see this fixed, so I don't want to minimize,
but also another workaround is to go ahead and join the subspaces,
which makes the rooms show in the ancestor space list as expected

**Comment by kittykat** [comment]
We had an internal discussion about this last week and will try using the severity/occurrence labels as if the feature is released, filtering on other labels to exclude Beta/Labs features from released features as and when needed.

**Comment by novocaine** [comment]
Possible workaround - auto-join parent sub-spaces on joining a room.

**Comment by afranke** [comment]
FWIW I don’t join subspaces on purpose. Spaces replace communities, and so I associate them with the same semantics. Just because I join a room that is part of a (sub)space/community doesn’t mean I feel like I am part of that space/community. Or to put it differently, I wouldn’t necessarily want to seen as a member of that group. The workaround of joining subspaces (automatically or not) doesn’t really solve the issue for me.

**Comment by novocaine** [comment]
Well .. it does solve the issue, right? You just don't want to be auto-joined to a subspace, which is fair enough.

**Comment by dbkr** [comment]
Another aspect of this is that sometimes the grandchild space just appears in your space panel for no reason I can see. Needless to say, having other spaces just show up in your space bar is somewhat disconcerting.
