### ISSUE TITLE
Threads filter does the opposite of what you select

### ISSUE THREAD

**Issue by robintown** [vector-im/element-web#23999]
### Steps to reproduce

1. Open the threads list
2. Select 'my threads' from the dropdown
3. Observe that the list still shows all threads
4. Select 'all threads' from the dropdown
5. Observe that the list now shows only threads you have participated in

#### What did you expect?

'My threads' should show my threads, and 'all threads' should show all threads

#### What happened instead?

'My threads' shows all threads, and 'all threads' shows my threads

### Operating system

NixOS unstable

### Browser information

Firefox 107.0.1

### URL for webapp

develop.element.io

### Application version

Element version: a7124c935ece-react-8869374c6bfb-js-447319737a05 Olm version: 3.2.12

### Homeserver

Synapse 1.72.0

### Will you send logs?

No

**Comment by justjanne** [comment]
This should have been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/9746

**Comment by t3chguy** [comment]
@justjanne `8869374c6bfb` is 4 days old, your change landed 5 days ago - I'm inclined to mark this as a release blocker

**Comment by t3chguy** [comment]
@justjanne could https://github.com/vector-im/element-web/issues/24040 be considered at the same time, alone probably not a release blocker but definitely backport-worthy

**Comment by daniellekirkwood** [comment]
While I'm sure this is confusing to users I don't believe it should be a release blocker - It's marked as Occasional and Minor which makes it a P3 issue. Also - users still have access to all their threads in the list (and many users are unaware of the drop down filter). 

It would however be great to get this fixed so if not in this release, the next would be ideal 👍

**Comment by t3chguy** [comment]
@daniellekirkwood the issue is it had a PR which claimed to fix it, which does not inspire confidence in the code quality and lack of tests. I doubt it deserves `Occasional` if we're pushing threads on-by-default - it is front and centre top of the thread list

**Comment by gsouquet** [comment]
@t3chguy the issue happens sporadically. There's ways to end up in that state, but it works most of the time! I'm investigating the issue, but it's more uncommon that occasional IMO

**Comment by gsouquet** [comment]
As discussed with @t3chguy it does most of the time the right thing but can end up in the state described in this ticket.
This is not a release blocker but should absolutely be fixed promptly.

**Comment by t3chguy** [comment]
I can no longer reproduce this
