### ISSUE TITLE
Application doesn't close to icon (no tray icon)

### ISSUE THREAD

**Issue by JackJeisly** [vector-im/element-web#23993]
### Steps to reproduce

1. Where are you starting? What can you see?
I start a Element Nightly and doesn't see icon in tray.

Doesn't work option "Show tray icon and minimise window to it on close". In "Preferences" this option are enabled. If I close window application just close.

#### What did you expect?
I expect that window will be closed to tray icon

#### What happened instead?
when I close window application just close.

### Operating system

Ubuntu Linux 20.04 LTS  

### Application version

Версия Element Nightly: 2022121401 Версия Olm: 3.2.12

### How did you install the app?

From repo "https://packages.element.io/debian/ default main"

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by G2G2G2G** [comment]
Yep happens to me in nightly as well on arch, something broke system tray icon in last few updates

it does stay running in the background fine, the icon just doesn't show up regardless

**Comment by G2G2G2G** [comment]
It doesn't even work on OpenSUSE KDE tumbleweed that I see.. (I use a WM on my main machine)
I assume what works is gnome, looks like other guy has XFCE working which is GTK too so maybe that's it.

looking at this comment https://github.com/electron/electron/pull/36471  
"we believe we've done a better job this time but I don't want to send this to an existing stable line" 
lol, yea definitely just needs a fallback to the libappindicator 

I only see mention of "StatusIconLinuxDbus" on chromium, and election nothing else.. there's a GTK.h file in some mailing list but it's part of electron too
Is it called something else? I'd add it to my WM

**Comment by JackJeisly** [comment]
>yea definitely just needs a fallback to the libappindicator
If it isn't work in popular distrs - needs a fallback to the libappindicator. And ideally fallback from electrone and chromium to C or C++. :)

**Comment by AffSeda** [comment]
Same issue on Debian testing/MATE. I assume this "StatusIconLinuxDbus" isn't just some package I can install ?

**Comment by G2G2G2G** [comment]
@AffSeda no, from what I see the "libappindicator" was the easy one that you could "just install" and it'd make everything work magically.

The new one they do now is something to do with this https://github.com/AyatanaIndicators/libayatana-indicator (which is linked to on the rocket chat github below)

This was supposed to be fixed when electron 22 is used, but I think it is already used and still didn't get fixed
Rocket chat and several other programs have the same issue, it's all cuz of electron stuff.
see here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2536#issuecomment-1364497357

Sooo unless my element user agent is wrong, we are on version 22 of electron and it still doesn't work, so no idea... unfortunately we can't just install something though

**Comment by mairacanal** [comment]
I'm also having this problem with Fedora 37/GNOME 43.2 and Element 1.11.17. I installed `libappindicator`, but it didn't solve my problem.

**Comment by AffSeda** [comment]
> @AffSeda no, from what I see the "libappindicator" was the easy one that you could "just install" and it'd make everything work magically.

That's unfortunate. I never thought the icon would annoy me that much.. but it actually does, lol. I keep losing the Element window, and for some reason sometimes my system opens a new Element instead of bringing the other window to the front if I relaunch it while it's running. I've downgraded for now.

**Comment by JackJeisly** [comment]
I frost Element updates on 1.11.16 too, becouse it normal work.

**Comment by G2G2G2G** [comment]
@AffSeda 
>and for some reason sometimes my system opens a new Element instead of bringing the other window to the front if I relaunch it while it's running. I've downgraded for now.

yea that's been a bug for like 2 years lol. It is a funny one, careful not to close the old one with the new one up or it'll delete your login session and reset both elements to default non logged in

**Comment by JokerGermany** [comment]
Same problem here.
Updated today to 1.11.17 and got this.
downgraded to 1.11.16 and tray icon is there again.

Really severe bug...

**Comment by JokerGermany** [comment]
Would be nice if you would stop the rollout for the linux version, this will be a support nightmare for me who support some people...

**Comment by JokerGermany** [comment]
> 



> @AffSeda
> 
> > and for some reason sometimes my system opens a new Element instead of bringing the other window to the front if I relaunch it while it's running. I've downgraded for now.
> 
> yea that's been a bug for like 2 years lol. It is a funny one, careful not to close the old one with the new one up or it'll delete your login session and reset both elements to default non logged in

Do you have an link to that issue? Think that happens to some of the peoples i support...

**Comment by mcuguy** [comment]
Same here. On Ubuntu.
The only way to have the icon back is to disable the option in Preferences|General and close Element.
Re-open Element and enable the icon again and it shows back.
Unfortunately, at the next opening it is not shown again, unless you remember to disable the option before closing and re-enabling it at the next run.
But still a bad workaround. Please fix it!!!

**Comment by G2G2G2G** [comment]
@JokerGermany no link, can't figure out how to reliably reproduce it so figuring out why it happens might be impossible - waste days on someone's time where they can be doing something of more importance
if I figure out exactly how to guarantee it opens a second one, I'd make an issue or just fix it myself

**Comment by FizzyTea** [comment]
I have attempted to downgrade to 1.11.16 using apt but this versions appears unavailable.
`sudo apt install element-desktop=1.11.16`
results in
`E: Version '1.11.16' for 'element-desktop' was not found`

Can I downgrade with apt or do I need to build from source? (Ubuntu 20.04 with XFCE)
`

**Comment by JokerGermany** [comment]
@FizzyTea 
If you use the 
https://packages-old.element.io/debian/pool/main/e/element-desktop/
Download it and then i used `sudo dpkg -i `

**Comment by FizzyTea** [comment]
> @FizzyTea https://packages-old.element.io/debian/pool/main/e/element-desktop/ Download it and then i use `sudo dpkg -i `


Thanks for your help.

**Comment by shivajiva101** [comment]
For the folks with this issue wishing to use v1.11.17 delaying Element-desktop startup for a few seconds fixes this issue at least on Kubuntu 22.04

Turning off the start with windows setting and scripting a delayed start makes element display the tray icon every time...

Detecting plasmashell load and immediately starting the app produces the same no tray icon bug.

I also noted that editing the startup entry and adding a delay fails after one restart when the startup entry gets rewritten by Element launching, so adding a custom delay there is pointless!

**Comment by AffSeda** [comment]
@shivajiva101 Hmm, I don't think you have the same bug? For me at least, Element was never set to run at startup. The method used to call the icon changed. Whether or not I start Element within 1 second of logging in, or after breakfast and a coffee, there will be no icon. Perhaps your desktop supports displaying the new type Icon, but has some other issue with consistently displaying it?

**Comment by shivajiva101** [comment]
@AffSeda Yes I agree, my appearance here is a consequence of the dev team closing #16760 in favour of this, possibly down to some ambiguous use of English. When the application is launched on startup it can be started as minimised to tray so I can see the crossover.

**Comment by Jieiku** [comment]
I ran into this after updating my arch install.

with element-desktop up press alt to show the title bar, then choose file > quit.

now relaunch element-desktop, and like magic the tray icon is back.

This was my experience under KDE Plasma, your mileage may vary.

I normally use system settings to launch element-desktop at boot, that still does not work for an icon. I am about to try delaying the launch of the application, or writing a custom script to launch it.

**Comment by G2G2G2G** [comment]
Lmao all these KDE issues.. KDE must have the newer API because it can work.. but the newer api must still be broken because it doesn't always work. What a great update from electron.

**Comment by JackJeisly** [comment]
The problem is not only in KDE. This problem in LXDE, XFCE, IceWm too. The tray icon doesn't work at all in those DEs. That's why I can't use new desktop version after 1.1.16.
Even if the update of electron is to blame for this problem - it's still a mistake of Element developers, who included it in new versions for Linux before the problem was solved. Although in my opinion the most critical mistake was made when someone decided to develop the messenger using the heavy, clumsy and resource-hungry electron.

**Comment by enigma9o7** [comment]
@JackJeisly Nobody's forcing you to use element, perhaps you would prefer nheko?  I think what G2 was saying is that the systray icon works sometimes in KDE Plasma.  For the rest of us, it NEVER works.

One thing this forced me to learn the keyboard command to exit electron, since without the tray icon there's no way to exit with mouse.  But like most others, I've reverted to previous version until this is resolved.

**Comment by G2G2G2G** [comment]
@JackJeisly nobody said it was only KDE... the KDE threads get closed and pointed here, so the KDE people keep coming here. They have a slightly different issue as I outlined.

**Comment by t3chguy** [comment]
> One thing this forced me to learn the keyboard command to exit electron, since without the tray icon there's no way to exit with mouse. But like most others, I've reverted to previous version until this is resolved.

You can also disable close to tray in Settings > Preferences so the window X will close the app fully

**Comment by JackJeisly** [comment]
@enigma9o7,  yes, i use Nheko now for most time. And the only thing I miss about it is the multi-account.

@G2G2G2G 
> But it doesn't have message threads if you use them.

I would use them if it looked like... like comments on YouTube, for example. But the way threads are made now, it's inconvenient, totally useless and unusable. IMHO

**Comment by G2G2G2G** [comment]
not really relevant to what I said.. and the threading is the same as virtually every other chat with threading

**Comment by FizzyTea** [comment]
Issue the same with v1.11.18 (ubuntu 20.04 xfce)

**Comment by Am6er** [comment]
rollback 1.11.20 -> 1.11.16 and freeze it with
`sudo apt-mark hold element-desktop`

**Comment by t3chguy** [comment]
This'll be fixed in the next electron 22.x release which adds a fallback to the old implementation

**Comment by G2G2G2G** [comment]
hilarious since that's what they thought they did this 2nd/3rd attempt.. guess 4th time's the charm!

**Comment by JackJeisly** [comment]
A better solution would be to replace electron xx.x with C, as Psi for Jabber ... dreams, dreams... ) At least this way...

**Comment by G2G2G2G** [comment]
@JackJeisly yea sounds easy enough, use nheko or make your own client

**Comment by JackJeisly** [comment]
No, it doesn't even sound simple enough. But in my mind, messenger is primarily for text and file sharing. For pictures with kitties, stickers and other shit - social networks. So the client should be easy and fast.
Most of the time I use xmmp with Psi, which is connected to Matrix via the Bifrost bridge. But I have some hipsters in my contacts when I need Element. Nheko is good, but it doesn't have sound notifications.  
Anyway, thank you very much to the developers for Element. It really is a tremendous effort.

**Comment by JackJeisly** [comment]
I updated Element-Nightly to: 
Element Nightly: 2023020301
Olm version: 3.2.12
No effect, no icon. (

And one yet moment. When trying to download logs from Element, I have IceWM crash. Maybe the problem is:

libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

(https://github.com/intel/libva/issues/518)? I don't think that's the problem though, chrome-based browsers work fine...

**Comment by t3chguy** [comment]
The fix landed after the nightly was built. So that is as expected.

**Comment by JackJeisly** [comment]
I updated to 1.11.22 - no effect, no icon. But the program works when the window is closed.
Downgrade to 1.11.16 again. (

**Comment by t3chguy** [comment]
@JackJeisly unfortunately time travel isn't real. The fix landed 6 hours ago. 1.11.22 shipped 3 days ago.

**Comment by JackJeisly** [comment]
I updated to 1.11.22 25 minutes ago.

**Comment by t3chguy** [comment]
The package was created 3 days ago. Whether you updated to it then or 2 days ago or 1 minute ago. It'll be the same thing. Packaged before the fix landed. 

![image](https://user-images.githubusercontent.com/2403652/216661196-6931a6f9-c379-4e84-a0fc-ac6541908661.png)

https://github.com/vector-im/element-desktop/releases/tag/v1.11.22

**Comment by JackJeisly** [comment]
I understan. I'll be try a next version, 23 and 24. Thanks!

**Comment by G2G2G2G** [comment]
@JackJeisly nightly will work now if you update to it.. 
tested on awesomeWM, and kde

>unfortunately time travel isn't real. 

maybe for the weaklings on earth, but us mooninites travel 1 second into the future every 1 second that passes

**Comment by JackJeisly** [comment]
Wow! It really works. 
Thank you very-very!
Now to waited multiacc, and it'll be good messenger. O... And yet separate proxy settings for each of accounts. 
Yes, i'm modest, i know. )

**Comment by InklingGirl** [comment]
My issue #24361 was closed & I was redirected here, only to find this issue has also been closed, all while the issue still persists for me on Ubuntu 22.04.1 w/ Gnome 42. Obnoxious. If there's been an update to fix this, it certainly hasn't been pushed to the project's Deb deployment repo I install `element-desktop` from…

**Comment by t3chguy** [comment]
@InklingGirl the fix landed 3 days after the last release, you'll need to wait for the next release. See above comments.

**Comment by JackJeisly** [comment]
@InklingGirl ,  i checked it in the last version of "element-nighly". Yes, it work.

**Comment by InklingGirl** [comment]
@t3chguy when is the ETA for a new release?

**Comment by t3chguy** [comment]
Every two weeks on a tuesday, next is scheduled to go into RC tomorrow, stable a week on tuesday.

**Comment by JokerGermany** [comment]
Is it in 1.11.23?
I don't find this in the patch notes:
> Update to Electron 22.2.0 - fix tray icons in Linux (https://github.com/vector-im/element-desktop/pull/530). Fixes https://github.com/vector-im/element-web/issues/23993.

**Comment by t3chguy** [comment]
@JokerGermany you might want to try Ctrl F

![image](https://user-images.githubusercontent.com/2403652/218724596-4ecd61a8-7ba2-431a-b587-4409a98f2873.png)

**Comment by JokerGermany** [comment]
¯\\_(ツ)_/¯ I tried Ctrl F, looks like i have other patchnotes:
![grafik](https://user-images.githubusercontent.com/30293477/218732651-4a6f221a-df1d-4fa2-9bb3-204014ee72e4.png)

**Comment by t3chguy** [comment]
@JokerGermany are you looking at the wrong repo maybe? Electron is only in the desktop repo as it doesn't affect the webapp.

**Comment by JokerGermany** [comment]
> @JokerGermany are you looking at the wrong repo maybe? Electron is only in the desktop repo as it doesn't affect the webapp.

ups yes, sorry didn't know that desktop has it's own release notes...

**Comment by Me4Linux** [comment]
Unfortunatley no tray icon on Debian 11 (XFCE) after updating to 1.11.23 yesterday. Funny enough the tray icon worked before installing that version … scratching my head … went back to 1.11.16 and the icon's back.
Same problem with the latest nightly version.

**Comment by aidaho** [comment]
> Unfortunatley no tray icon on Debian 11 (XFCE) after updating to
> 1.11.23 yesterday. Funny enough the tray icon worked before
> installing that version … scratching my head … went back to 1.11.16
> and the icon's back. Same problem with the latest nightly version.
> 

Are you sure you've terminated all Element processes?  
I had to run `killall -v element-desktop` after closing the main window
in order to actually get an updated Electron instance.

I can confirm the tray icon is back in Debian 11/TDE with Element
1.11.23

**Comment by GitMeier** [comment]
Element version: 1.11.23
Olm version: 3.2.12

Tray icon is back on Ubuntu 20.04.5 LTS (focal)

**Comment by InklingGirl** [comment]
It is back for me too on Ubuntu 22.04.1 LTS (Jammy Jellyfish).

**Comment by floviolleau** [comment]
Hi,

I have the issue on Ubuntu Budgie 22.10
Element version: 1.11.23
Olm version: 3.2.12

Any clues?

**Comment by enigma9o7** [comment]
If you're new to element, you could confirm its the same issue by testing 1.11.16 and making sure its working there.... cuz I think this issue is fixed for the rest of us.

**Comment by Me4Linux** [comment]
Hi, folks,

during the weekend I've tested the new version 1.11.23 on my second PC (Debian 11, XFCE). Works without problems, icon's back in the tray.
But today in the office (Debian 11 and XFCE, like the other computer) I upgraded again from 1.11.6 to 1.11.23, restartet the machine and the problem's back - no icon in the tray but element is running. Purged the new version and reinstalled 1.11.16 and the icon is back. The same happens with both the Flatpak and the Debian package.

I'm starting to suspect there may be a problem just with that specific PC (maybe unregarded with element?).

**Comment by rwjack** [comment]
```
~ ❯ element-desktop
...
```
Icon is in taskbar, but element is blurry because running in wayland
![image](https://user-images.githubusercontent.com/59068073/221917742-d297986a-b9d5-4210-b750-a2536dfd0402.png)

```
~ ❯ element-desktop -enable-features=UseOzonePlatform --ozone-platform=wayland
...
```

Icon missing in taskbar, but element is sharp as a crystal
![image](https://user-images.githubusercontent.com/59068073/221917955-a3d86f15-e58e-4922-947a-af0034c8be96.png)


Is this related to this issue?

**Comment by floviolleau** [comment]
Hi,

I have another computer on Ubuntu 22.10
Element version: 1.11.23
Olm version: 3.2.12

And it is working fine, I have the tray icon (despite the blank screen at start up which is another issue).

**Comment by drskalman** [comment]
It still does not show up in my tray. 

Arch Linux
element-desktop 1.11.26-1
exwm 

Downgrading to element-web-1.11.10-2 resolves the problem (I don't have 11.16 package cached). I have also no problem with nextcloud and other apps in my tray.

**Comment by t3chguy** [comment]
@drskalman the arch package is community maintained, please report issues with it to its maintainer.

**Comment by G2G2G2G** [comment]
@drskalman this isn't an issue anymore, it's your system. I have it working across different WMs and DEs on different machines

**Comment by jahway603** [comment]
Still having this issue. It was never resolved.

**Comment by jahway603** [comment]
This PR https://github.com/vector-im/element-desktop/pull/530 shows that an "upgrade" to Electron 22.x occurred that fixed this issue. I have Electron 25.x & this is still an issue. Any ideas?

**Comment by Mi-La** [comment]
I just installed the electron app on xubuntu for the first time and I have no tray icon. I don't care if it's problem of my particular system, it's still the FIRST TIME USER EXPERIENCE.

**Comment by shivajiva101** [comment]
If you're coming here because this issue isn't fixed for your system build, maybe try an alt matrix client such as Schildichat it might not be bleeding edge, but that isn't necessarily a problem.

 If you're capabilities include scripting, don't use the Element setting, just launch Element after a few seconds delay with a script and the tray icon will be present every time. At least that is what consistently works for me. An easy test to check if delayed start works on your system is to disable launch on startup and manually launch it after a reboot. If Element launches with a tray icon present then scripting a delayed start will definitely work. Reducing the delay in the script below a threshold that's likely system specific, 5 seconds for my system, does duplicate the issue of a launched process with no tray icon to access it.

**Comment by Mi-La** [comment]
It simply doesn't work even when I run Element manually. It works e.g. with Nheko, but Nheko is not based on Electron. Schildichat has the same problem. There are various issues across github related to the Electron + tray icon + libappindicator, but I wasn't able to fix it in a reasonable time. 
I just don't understand why the issue is closed while it clearly doesn't work for more users.

**Comment by Mi-La** [comment]
Ok .. after yet more struggling I've seen the tray icon for the first time! So for others (maybe related only to *Xubuntu* users):

First I've found this topic on the XFCE forum:  https://forum.xfce.org/viewtopic.php?id=16436. It leads to the following bug report: https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/599.

When I removed the **ayatana-indicator-application** which I've never installed (probably was installed automatically since it's recommended by xfce4-indicator-plugin which is recommend by ...).

Hope it helps to someone else! I'll give the element-desktop a try :-).
