### ISSUE TITLE
Message editing: Ensure the timeline layout doesn't change when editing

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#9752]
New design:

![EditingV2](https://user-images.githubusercontent.com/4626865/57930463-f36a0e00-78ad-11e9-9760-b5deb6b56a27.gif)

- [x] Edit UI shouldn't impact timeline layout, leaving a gutter on the right for read receipts
- [ ] Z index should ensure the Edit UI is above the composer, and below the room header
- [x] Adding new lines should grow upwards (as now)

**Comment by bwindels** [comment]
> Edit UI shouldn't impact timeline layout, leaving a gutter on the right for read receipts

should be addressed by https://github.com/matrix-org/matrix-react-sdk/pull/2996

> Z index should ensure the Edit UI is above the composer, and below the room header

Postponed this for now.

**Comment by bwindels** [comment]
I think the plan is to have another look at the layout of the edit UI (what Matthew said AFAIR), so postponing the remaining overlay work.

**Comment by nadonomy** [comment]
I remember we had some discussion about not having the bottom left of the panel occlude the timeline but arrived at a place where that direction didn't make sense as (a) it's ok to occlude the message below, as you're interacting with edits contextually (b) it would be inconsistent with the rest of the UI and (c) it robs us of a sensible place to put the formatting legend.

@ara4n can you be more specific about what you wanted to take another look at?

**Comment by bwindels** [comment]
For context, matrix discussion:
> Matthew: i'm relatively happy with the current edit UI ftr
it's irritating that the layout pops when you edit the most recent message (which is the common case) due to making room for the buttons
and i'd still prefer they were put in the right margin rather than below (hence the popping fun)
but it's not the end of the world

Also postponing this because it is likely difficult to implement and doing other feature work in phase:3 feels like it would be a bigger pay-off.

**Comment by ara4n** [comment]
i'm still not entirely convinced that occluding the content below is necessary or desirable, and it certainly makes implementation harder for stuff like occluding the composer.  totally agreed that this is low prioity though.

**Comment by nadonomy** [comment]
Just had a thought— the right gutter approach could work if we use icon based buttons and colour to provide more contrast for the eye (green tick button, red cancel). I'll do a comp in due course and we can see how we feel about it, perhaps with us in-lining/absolute positioning the formatting legend within the composer chrome.

**Comment by bwindels** [comment]
Sgtm. Wrt to the legend, I think the idea is also to display it in the main composer in the future.
